fix

diff --git a/.github/workflows/docker-test.yaml b/.github/workflows/docker-test.yaml
--- a/.github/workflows/docker-test.yaml
+++ b/.github/workflows/docker-test.yaml
@@ -111,6 +111,21 @@ jobs:
       - name: Generate Excel Report and Upload to Slack
         run: python src/report/generate_excel_report.py
 
+      - name: 백업 이전 결과 정리
+        run: |
+          today=$(date +'%Y-%m-%d')
+          mkdir -p backup/reports/$today
+          mkdir -p backup/screenshots/$today
+          mv test-report_*.xlsx backup/reports/$today/ || echo "✅ 백업할 엑셀 없음"
+          if [ -d failed_screenshots ]; then
+          mv failed_screenshots/* backup/screenshots/$today/ || echo "✅ 백업할 스크린샷 없음"
+          else
+          echo "✅ failed_screenshots 폴더 없음"
+          fi 
+        
+        
+        
+
       - name: Upload Excel Report as Artifact
         uses: actions/upload-artifact@v4
         with:
@@ -120,27 +135,27 @@ jobs:
       - name: Force Update GitHub Pages
         run: echo $(date) > allure-report/timestamp.txt
 
+      - name: 결과물 복사
+        run: |
+          mkdir -p deploy_dir
+          cp -r allure-report deploy_dir/
+
 
       - name: Upload Allure report to Github Pages #리포트 업로드
         uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: allure-report/docker
-          destination_dir: docker
-          keep_files: true #기존파일 유지
+          publish_dir: deploy_dir
+          destination_dir: .
+          keep_files: false #기존파일 유지
 
 
-      - name: Send Slack Notification # Slack 알람
-        uses: rtCamp/action-slack-notify@v2
+      - name: Send Slack Test Summary
+        run: |
+          pip install requests
+          python utils/send_slack_result.py
         env:
-          SLACK_WEBHOOK: ${{ secrets.QA_SLACK_WEBHOOK_URL }}
-          SLACK_USERNAME: "GitHub Actions"
-          SLACK_ICON_EMOJI: ":robot_face:"
-          SLACK_TITLE: "✅ Docker Test 완료"
-          SLACK_MESSAGE: |
-            *📢 Docker Test 테스트가 끝났습니다!*
-            *📄 리포트 확인*: <https://yoplekiller.github.io/QATEST/allure-report/docker/index.html>
-          SLACK_COLOR: "#36a64f"
+          SLACK_WEBHOOK_URL: ${{ secrets.QA_SLACK_WEBHOOK_URL }}
 
       - name: Check available memory
         run: free -h
