fix

diff --git a/.github/workflows/selenium-test.yaml b/.github/workflows/selenium-test.yaml
--- a/.github/workflows/selenium-test.yaml
+++ b/.github/workflows/selenium-test.yaml
@@ -39,6 +39,11 @@ jobs:
         run: |
           mkdir -p allure-results
           venv/bin/python -m pytest src/tests/ui_tests --alluredir=$(pwd)/allure-results
+          
+
+      - name: Debug Allure Results
+        run: |
+          ls -l allure-results || echo "❌ allure-results directory is missing!"
 
 
       - name: Install Allure CLI # Allure CLI 설치
